# The plugin is in testing and may be unstable and / or buggy, Please report any bugs or errors to the Bukkit dev page so we can squat them
# as soon as possible :)

Locale: en

SignHeaderBuy: [BuyRegion]
SignHeaderRent: [RentRegion]
BuyRegionMax: 0
CheckExpirationsInMins: 5
RequireBuyMode: true
RentRegionMax: 0
RequireBuyPerms: false
RequireRentPerms: false
# DateFormat values: Default, US or EU
DateFormat: Default