name: BuyRegion
version: @version@
main: com.region.buyregion.BuyRegion
api-version: 1.13
depend: [Vault]
softdepend:
  - WorldGuard
  - RedProtect
authors: [GentleGravel, Luke199]
description: WorldGuard/RedProtect Region Sales
commands:
  buyregion:
    description: toggles region buy or rent mode.